apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1 # number of similar pods we want to run
  selector: # tells the deployement which pods to use.
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
      - name: query
        image: diracmmd/query

---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002 # The port that nodePort uses to map the traffic to the container
      targetPort: 4002 #The port where our container is runing

---

apiVersion: v1
kind: Service
metadata:
  name: query-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002 # The port that nodePort uses to map the traffic to the container
      targetPort: 4002 #The port where our container is runing